src/avx512-16bit-qsort.hpp
src/avx512-32bit-qsort.hpp
src/avx512-64bit-qsort.hpp
src/avx512-common-qsort.h

compiler in Cygwin has a bug which causes segmentation fault. See comments: https://github.com/numpy/numpy/pull/22315#issuecomment-1267234980 and https://github.com/numpy/numpy/pull/22315#issuecomment-1267757584
Work around it to force inline avx-512 code.

Force inline on cygwin only

---

Makefile
src/avx512-64bit-keyvaluesort.hpp
tests/main.cpp
tests/test_keyvalue.cpp
tests/test_qsort.cpp
utils/cpuinfo.cpp
utils/cpuinfo.h
utils/rand_array.h

1) Adding `get_uniform_rand_array_with_uniquevalues` for random arrays with unique values
2) split tests into separate files

MAINT: cleanup code and split tests

---

benchmarks/meson.build
meson.build
tests/meson.build

Required to check availability of both compiler and assembler.

update meson.build to ensure AVX-512 FP16 can be compiled

---

src/avx512-16bit-common.h
src/avx512-32bit-qsort.hpp
src/avx512-64bit-common.h
src/avx512-64bit-qsort.hpp
src/avx512-common-qsort.h
tests/test_keyvalue.cpp
tests/test_partial_qsort.hpp
tests/test_qselect.hpp
tests/test_qsort.hpp
tests/test_qsortfp16.cpp
tests/test_sort.cpp

- Add a larger network oto see if it helps at all.  
- Added an unrolled version of partition_avx512 (based on https://github.com/simd-sorting/fast-and-robust/blob/054f2e2e9f7c00be4dc8d69567f92ddf9832a8f3/avx2_sort_demo/avx2sort.h#L774). 
benchmark comparison: 
up-to 1.64x speed up for `avx512_qsort`, `avx512_qselect` and `avx512_partial_qsort `using the unrolled avx512_partition: 
```
Benchmark                                             Time             CPU      Time Old      Time New       CPU Old       CPU New
----------------------------------------------------------------------------------------------------------------------------------
avx512_qsort<double>/10000                         -0.2855         -0.2855         80600         57586         80608         57595 …
```

Improve qsort

---

src/avx512-64bit-argsort.hpp
src/avx512-64bit-common.h
tests/test_argsort.cpp

Skip avx-512 argsort for arrays with NAN 

---

src/avx512-64bit-common.h

g++-7 is missing the _mm256_storeu_epi32 intrinsic.

Replace intrinsic missing from g++-7

---

.github/workflows/c-cpp.yml
.gitignore
Makefile
benchmarks/main.cpp
meson.build

Basically I got annoyed that my Ubuntu 20.04 machine couldn't compile the benchmarks so I looked into it. I also updated the Makefile to have some available compiler smarts like Meson. Closes #44.
---
On systems with glibc < 2.34, the `-lpthread` option needs to be included when linking with Google's benchmark and test frameworks. However, the `pkg-config` command for `benchmark` needs to be explicitly given the `--static` flag for this to be included. The static inclusion has also been added to the Meson configuration.
I've also included some rudimentary logic to allow the Makefile to shrink the scope of its compilation targets when an older compiler is being used. I changed the benchmarks to run using `benchmark_main` in the same way that the tests use `gtest_main`. Finally, I turned …

Update build configuration to reduce friction

---

src/avx512-16bit-qsort.hpp
src/avx512-32bit-qsort.hpp
src/avx512-64bit-qsort.hpp
src/avx512-common-qsort.h
src/avx512fp16-16bit-qsort.hpp
tests/test-qsort-fp.hpp
tests/test-qsort.cpp

- Preprocess array at the beginning and move all the nans to end of the array
- Sort just the remaining elements.

Preserve NAN's in avx512_qsort

---

src/avx512-16bit-qsort.hpp
src/avx512-32bit-qsort.hpp
src/avx512-64bit-qsort.hpp
src/avx512-common-qsort.h
src/avx512fp16-16bit-qsort.hpp

Handling NAN's slows down the algorithm. We make it an optional argument. Also fixes a bug in qselect and partialsort where NAN's were handled incorrectly. Improved benchmarks for float and doubles not containing NAN's:
```
Benchmark                                                                  Time             CPU      Time Old      Time New       CPU Old       CPU New
-------------------------------------------------------------------------------------------------------------------------------------------------------
[avx512_qselect<double> vs. avx512_qselect<double>]/10                  -0.1488         -0.1488          8922          7594          8928          7600
[avx512_qselect<double> vs. avx512_qselect<double>]/100                 -0.1542         -0.1540          8963 …
```

Add an optional argument "hasnan" for qselect and partialsort

---

.github/workflows/c-cpp.yml

Google's Benchmark project has rearranged some of the files we need for the testing workflows. This commit points pip towards to correct requirements.txt for the latest versions of the framework. Alternatively, we could use `-b <name>` to ensure we always use the same version of the benchmark dependency.
```diff
mosullivan@melchior:~/source/repos/googlebenchmarks> git diff v1.8.0:requirements.txt HEAD:tools/requirements.txt
diff --git a/requirements.txt b/tools/requirements.txt
index 1c8a4bd..afbc596 100644
--- a/requirements.txt
+++ b/tools/requirements.txt
@@ -1,2 +1,2 @@
-numpy == 1.22
+numpy == 1.25
scipy == 1.5.4
```

Update workflow for changes in benchmark tooling

---

.gitignore
Makefile

I am mostly using GNU make at the moment, so I eventually found a few other things I thought might be worth changing. Feel free to disagree, e.g. if you think some of the changes could make maintaining the file problematic in the future.
An overview of the commits:
1. 5041188: Improve modularity of GCC compatibility resolution
- This uses a Makefile macro (`test_cxx_flag`) to allow checking an arbitrary flag of the GCC C++ compiler. AVX512-FP16 can be disabled without immediately falling back to `march=icelake-client`.
- There is the potential to intelligently downgrade the target architecture further, but that might make removing the affected tests a bit more difficult (e.g. Could potentially handle this with preprocessor directives).
2. d0623a7: Substantially update Makefile to improve …

Further Makefile updates

---

meson.build
src/avx512-16bit-qsort.hpp
src/avx512-32bit-qsort.hpp
src/avx512-64bit-argsort.hpp
src/avx512-64bit-common.h
src/avx512-64bit-keyvaluesort.hpp
src/avx512-64bit-qsort.hpp
src/avx512-common-argsort.h
src/avx512-common-qsort.h
src/avx512fp16-16bit-qsort.hpp
tests/test-keyvalue.cpp

MAINT: Remove template specializations for quicksort methods

---

README.md

This fixes the readme to reflect the current actual behavior. `avx512_qsort` behaves differently from `argsort` and `qselect`, and I'm not sure if that's intentional. #49 changed the behavior to move the bit-exact NaNs to the end of the array for those two functions only.
I also reworded it to state that the behavior is undefined if `hasbool=false` but the input has NaNs. That's the case because:
* If the fallback to `std::sort` is encountered, there's no defined behavior w.r.t. NaNs.
* The bitonic networks use `vminps`/`vmaxps`, which produce the second operand if one operand is NaN, and which value is the second operand varies.

Correct documentation on NaN behavior

---

src/avx512-64bit-argsort.hpp
src/avx512-64bit-common.h
src/avx512-64bit-keyvalue-networks.hpp
src/avx512-common-argsort.h
src/avx512-common-qsort.h

Ref: 
1. https://www.intel.com/content/www/us/en/developer/articles/technical/software-security-guidance/technical-documentation/gather-data-sampling.html
2. https://www.phoronix.com/review/downfall

Use scalar emulation of gather instruction for arg methods

---

lib/x86simdsort-avx2.cpp
lib/x86simdsort.cpp
src/avx2-32bit-qsort.hpp
src/avx2-64bit-qsort.hpp
src/avx2-emu-funcs.hpp

This adds support for 64 bit signed and unsigned integers as well as double.
```
Benchmark                                                                 Time             CPU      Time Old      Time New       CPU Old       CPU New
------------------------------------------------------------------------------------------------------------------------------------------------------
[scalarsort.*random vs. simdsort.*random]_128/uint64_t                 +0.2167         +0.2168          1473          1792          1474          1794
[scalarsort.*random vs. simdsort.*random]_256/uint64_t                 +0.4015         +0.4024          2238          3137          2239          3140
[scalarsort.*random vs. simdsort.*random]_512/uint64_t                 +0.4101         +0.4104          4017 …
```

AVX2 64-bit support

---

scripts/bench-compare.sh
scripts/branch-compare.sh
src/avx2-64bit-qsort.hpp
src/avx2-emu-funcs.hpp

Improves benchmarks by about 1.25x.
```
Benchmark                                                                   Time             CPU      Time Old      Time New       CPU Old       CPU New
--------------------------------------------------------------------------------------------------------------------------------------------------------
[simdsort/random_.*int64_t vs. simdsort/random_.*int64_t]                -0.1597         -0.1595         61073         51322         61080         51340
[simdsort/random_.*int64_t vs. simdsort/random_.*int64_t]                -0.1482         -0.1482       1926998       1641449       1926924       1641282
[simdsort/random_.*int64_t vs. simdsort/random_.*int64_t]                -0.1385         -0.1386      23119151      19916947      23117303 …
```

Improve emulation of AVX2 min/max 64-bit 

---

src/avx2-emu-funcs.hpp

This avoids using masked stores when unmasked stores can be used. This gives a reasonable performance improvement for AVX2 quicksort.
```
Benchmark                                                          Time             CPU      Time Old      Time New       CPU Old       CPU New
-----------------------------------------------------------------------------------------------------------------------------------------------
[simdsort vs. simdsort]/smallrandom_128/uint64_t                +0.0016         +0.0018          1495          1498          1499          1502
[simdsort vs. simdsort]/smallrandom_256/uint64_t                -0.0116         -0.0120          2680          2649          2685          2653
[simdsort vs. simdsort]/smallrandom_512/uint64_t                -0.0341 …
```

Avoid masks when possible in AVX2 logic

---

benchmarks/bench-all.cpp
benchmarks/bench-objsort.hpp
lib/x86simdsort.h
run-bench.py

Benchmarks sorting an array of 2D and 3D cartesian coordinates: 
```
Benchmark                                Time             CPU   Iterations                                                                                          [35/27249]
--------------------------------------------------------------------------
scalarobjsort<Point2D>/1000          54107 ns        54100 ns        12908
scalarobjsort<Point2D>/10000       1172135 ns      1172105 ns          597
scalarobjsort<Point2D>/100000     14652163 ns     14651279 ns           48
scalarobjsort<Point2D>/1000000   174384347 ns    174363797 ns            4
scalarobjsort<Point2D>/10000000 2042991245 ns   2042818194 ns            1
scalarobjsort<Point3D>/1000          54005 ns        53998 ns        12886
scalarobjsort<Point3D>/10000 …
```

Add API to sort array of custom objects

---

.github/workflows/build-numpy.yml
src/avx512-16bit-qsort.hpp
src/avx512-64bit-argsort.hpp
src/avx512fp16-16bit-qsort.hpp
src/xss-common-includes.h

@Flamefire please review if you can :) This alone won't fix the NumPy build, I will have a patch for that soon.

Mark explicit template specializations inline

---

benchmarks/bench-objsort.hpp
run-bench.py
scripts/bench-compare.sh
scripts/branch-compare.sh
src/avx512-32bit-qsort.hpp
src/avx512-64bit-keyvaluesort.hpp
src/xss-network-keyvaluesort.hpp

1. AVX-512 32-bit key value sort now uses zmm registers exclusively
2. Added `partition_avx512_unrolled` function
3. Use `get_pivot_blocks` function in key-value sort. 
Performance numbers: 
```
Benchmark                                                                  Time             CPU      Time Old      Time New       CPU Old       CPU New
-------------------------------------------------------------------------------------------------------------------------------------------------------
[simdkvsort/random_1m vs. simdkvsort/random_1m]/uint64_t                -0.2048         -0.2048      21833844      17362725      21833373      17361179
[simdkvsort/random_1m vs. simdkvsort/random_1m]/int64_t                 -0.2099         -0.2099      21922325      17320157      21919807 …
```

Improve key-value sort performance

---

src/xss-common-argsort.h
src/xss-common-includes.h
src/xss-network-keyvaluesort.hpp

compiler on macOS doesn't implicitly convert `zmm_vector<size_t>` to `zmm_vector<uint64_t>`

Build fix on macOS 64-bit

---

src/avx512-64bit-common.h
src/xss-common-argsort.h
src/xss-common-includes.h
src/xss-network-keyvaluesort.hpp

on 64-bit macOS, `size_t` is `unsigned long` and `uint64_t `is mapped to `unsigned long long` (both of which are 8 bytes in size). This causes build failures because the compiler refuses to map  `zmm_vector<size_t>` to `zmm_vector<uint64_t>`.

Fix more build issues on macOS

---

.github/workflows/build-numpy.yml
benchmarks/bench-objsort.hpp
lib/x86simdsort.h

Improves performance especially when the metric to sort is a 32-bit dtype: 
```
Benchmark                                                                            Time             CPU      Time Old      Time New       CPU Old       CPU New
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
[scalarobjsort.*float vs. simdobjsort.*float],x>>/100                             +0.0933         +0.0947          1419          1551          1421          1555
[scalarobjsort.*float vs. simdobjsort.*float],x>>/1000                            -0.3962         -0.3965         15418          9309         15431          9313
[scalarobjsort.*float vs. simdobjsort.*float],x>>/10000 …
```

Use uint32_t instead of size_t for object sort

---

src/avx2-32bit-qsort.hpp
src/avx2-64bit-qsort.hpp
src/avx512-16bit-qsort.hpp
src/avx512-32bit-qsort.hpp
src/avx512-64bit-common.h
src/avx512fp16-16bit-qsort.hpp
src/xss-common-includes.h
src/xss-common-qsort.h
src/xss-network-keyvaluesort.hpp
src/xss-network-qsort.hpp
src/xss-optimal-networks.hpp
src/xss-pivot-selection.hpp
tests/test-keyvalue.cpp
tests/test-objqsort.cpp
tests/test-qsort.cpp

This changes the pivot selection algorithm to give better results when handling special cases, with only a minimal impact on random sorting performance
5d benchmarks (50% random data, 50% 0)
```
---------------------------------------------------------------------------------------------------------------------------------------------------
[simdsort/random_5d vs. simdsort/random_5d]/uint64_t                -0.8243         -0.8242        151220         26569        151234         26580
[simdsort/random_5d vs. simdsort/random_5d]/int64_t                 -0.9165         -0.9165        334204         27897        334232         27903
[simdsort/random_5d vs. simdsort/random_5d]/uint32_t                -0.8788         -0.8788        135372         16402        135385         16406 …
```

New pivot selection algorithm to better handle many special cases

---

src/avx2-32bit-qsort.hpp
src/avx2-64bit-qsort.hpp
src/avx512-16bit-qsort.hpp
src/avx512-32bit-qsort.hpp
src/avx512-64bit-common.h
src/avx512fp16-16bit-qsort.hpp

This will correct new clang-formatting issues in the repository, allowing for CI to become green.

Clang-formatting fixes for Green CI

---

.github/workflows/build-numpy.yml
.github/workflows/scorecard.yml

I've been getting erroneous emails with cron-based github actions failing based off this repo. It seems that my fork is running the github actions as well. This can be stopped by adding an if statement to the cron-based github actions based on the github repository.  These actions with the if statement will only work on intel/x86-simd-sort.
I don't know if this was a desired behavior, and maintainers can change the PR as they wish. This is only a suggestion.
Note, this will be useful for people who fork this repo in the future, or update their fork's main branch.

[fix] key cron-based github actions to run only on intel/x86-simd-sort repo

---

lib/x86simdsort.h

Fixes the 32-bit linux CI failure

Specify size of key array at initialization

---

src/avx512-64bit-keyvaluesort.hpp
src/xss-common-argsort.h
src/xss-common-qsort.h

Our key-value tests don't cover NAN's and looks like a bug snuck through.

Fix bug while processing NAN in key-value sort

---

README.md
benchmarks/bench-argsort.hpp
lib/x86simdsort-avx2.cpp
lib/x86simdsort-internal.h
lib/x86simdsort-scalar.h
lib/x86simdsort-skx.cpp
lib/x86simdsort.cpp
lib/x86simdsort.h
src/README.md
src/xss-common-argsort.h
tests/test-qsort.cpp

This patch adds support for descending argsort and tests for it.
```
Comparing simdargsort.*random_1 to simd_revargsort.*random_1 (from ./benchexe)
Benchmark                                                                           Time             CPU      Time Old      Time New       CPU Old       CPU New
----------------------------------------------------------------------------------------------------------------------------------------------------------------
[simdargsort.*random_1 vs. simd_revargsort.*random_1]28/int64_t                  +0.0351         +0.0352           700           724           700           724
[simdargsort.*random_1 vs. simd_revargsort.*random_1]k/int64_t                   +0.0106         +0.0106         10495         10607         10495         10606 …
```

Adds descending order sort to argsort

---

lib/x86simdsort-avx2.cpp
lib/x86simdsort-skx.cpp
lib/x86simdsort.cpp
src/avx2-32bit-qsort.hpp
src/avx512-64bit-common.h
src/x86simdsort-static-incl.h
src/xss-common-keyvaluesort.hpp
src/xss-common-qsort.h
src/xss-network-keyvaluesort.hpp

This patch adds support for AVX2 key-value sorting. For comparison, benchmarks comparing the AVX2 vs. AVX512 performance and AVX2 vs. scalar performance are below:
<details>
<summary><b>AVX2</b></summary>
```
--------------------------------------------------------------------------
Benchmark                                Time             CPU   Iterations
--------------------------------------------------------------------------
simdkvsort/random_128/uint64_t        1939 ns         1946 ns       360240
simdkvsort/random_1k/uint64_t        18021 ns        18029 ns        39110
simdkvsort/random_100k/uint64_t    2359494 ns      2359426 ns          298
simdkvsort/random_1m/uint64_t     27181339 ns     27180247 ns           26
simdkvsort/random_10m/uint64_t   328366429 ns    328336094 ns …
```

AVX2 Support for key-value sorting

---

lib/x86simdsort-internal.h
meson.build

Introduced in 67c7534bfcb277368502f1d496a6c1075542b645

Hide keyvalue_qsort symbols in shared library

---

Makefile

Split different configurations of meson

Minor changes to Makefile

---

README.md
benchmarks/bench-keyvalue.hpp
lib/x86simdsort-avx2.cpp
lib/x86simdsort-internal.h
lib/x86simdsort-scalar.h
lib/x86simdsort-skx.cpp
lib/x86simdsort.cpp
lib/x86simdsort.h
src/x86simdsort-static-incl.h
src/xss-common-keyvaluesort.hpp
src/xss-common-qsort.h
tests/test-keyvalue.cpp
tests/test-qsort.cpp
utils/custom-compare.h

This patch adds support for descending kv-sort and ascending/descending kv-select and kv-partial_sort
For reference, some benchmarks comparing to Pytorch's scalar implementation are provided:
With normally distributed float32:
```                                                                          
Partial Sort (sorted topk):                                                                           
size           default        avx2           avx512         AVX2 speedup % AVX512 speedup %
16             4.180374384    4.0826931      4.202754736    -2.336663537   0.53536717     
128            5.362578869    6.11398387     5.229052782    14.01200838    -2.489960336   
1024           14.10357333    14.0685565     9.240571122    -0.248283326   -34.48063899   
10000          322.740033 …
```

Adds support for kv-select, kv-partial sort, and descending order for all key-value functions.

---

.github/workflows/c-cpp.yml
Makefile
lib/meson.build
meson.build
meson_options.txt
scripts/branch-compare.sh
src/xss-common-keyvaluesort.hpp

This patch adds support for OpenMP parallelized kv-sort, and adds a new GitHub CI run to test this logic. 
Below are benchmarks, ran with OpenMP limited to 8 threads. Note that for the smaller sizes, no parallelization is occurring, they are simply here to show there isn't a significant regression for smaller arrays.
<details>
<summary><b>10m</b></summary>
```
Benchmark                                                                    Time             CPU      Time Old      Time New       CPU Old       CPU New
---------------------------------------------------------------------------------------------------------------------------------------------------------
[simdkvsort/random_10m vs. simdkvsort/random_10m]/uint64_t                -0.6970         -0.7395     226436121      68612307 …
```

Adds OpenMP based parallelization to key-value sorting

---

lib/x86simdsort.cpp
src/avx2-64bit-qsort.hpp
src/avx512-64bit-common.h

There are two primary changes included here. This commit aims to address #156 
This commit includes OpenBSD in the platform checks used to check for size_t, uint64_t, unsigned long and unsigned long long all being 64 bits in length.
Consider the following C code compiled and run on the target platform
```c
#include <unistd.h>
#include <stdio.h>
int
main(int argc, char **argv)
{
printf("sizeof(unsigned long) = %d\n", sizeof(unsigned long));
printf("sizeof(long) = %d\n", sizeof(long));
printf("sizeof(int64_t = %d\n", sizeof(int64_t));
printf("sizeof(unsigned long long) = %d\n", sizeof(unsigned long long));
printf("sizeof(uint64_t) = %d\n", sizeof(uint64_t));
printf("sizeof(long *) = %d\n", sizeof(long *));
printf("sizeof(uint64_t *) = %d\n", sizeof(uint64_t *));
return 0;
}
```
When …

Add flags to support OpenBSD

---

src/README.md

This pull request fixes some mistakes in the previous documentation, and reflects recent API changes.
1. AVX2 now also has `argsort`, `argselect`, and key-value sort.
2. Adds the missing argument `k` in `qselect` and `partial_qsort`.
3. The version of `argsort` that returns a `std::vector` has been removed. Similar for `argselect`.
4. Fixes the template parameters in `avx512_qsort_kv`.
5. The sample code needs to include some `xss-common-*` headers to compile.

Documentation fixes

---

.github/workflows/build-numpy.yml
.github/workflows/c-cpp.yml
.github/workflows/linting.yml
.github/workflows/scorecard.yml
src/xss-common-keyvaluesort.hpp
tests/test-keyvalue.cpp

Fixes the bug with nested OpenMP by adding #pragma omp taskwait
Changes the task_threshold when OpenMP is enabled but parallelization isn't chosen from 0 to the max value for arrsize_t; I don't think this was causing any problems, but it was definitely a mistake
Additionally, extended the kvsort tests to also run for sizes of 10^4, 10^5, 10^6 for testing the OpenMP logic

Fixes bug with nested OpenMP, fixed task threshold, extended tests range

---

src/avx2-32bit-half.hpp
src/avx512-64bit-common.h
src/xss-common-keyvaluesort.hpp
src/xss-pivot-selection.hpp
utils/rand_array.h

Adds smart pivot selection to key-value sorting, improving performance in some cases like when one value is extremely common. This gives around a 10x performance improvement when half the data is 0.

Adds smart pivot selection to key-value sorting

---

README.md
src/xss-common-argsort.h

Adds an `_mm_empty()` intrinsic to generate `emms` when MMX is enabled in argsort/argselect, which should resolve the potential for issues described in #154.
As far as I can determine, this has no significant performance impact
<details>
<summary><b>Performance Comparison</b></summary>
```
Comparing simdargsort (from /home/msterrett/xss/newperf/x86-simd-sort/.bench/main/builddir/benchexe) to simdargsort (from /home/msterrett/xss/newperf/x86-simd-sort/.bench/mmx_fix/builddir/benchexe)
Benchmark                                                                Time             CPU      Time Old      Time New       CPU Old       CPU New
----------------------------------------------------------------------------------------------------------------------------------------------------- …
```

Fix for MMX instructions being generated without emms

---

example.c
lib/x86simdsort.cpp

Also added an example file to demonstrate how to use it.

Expose C-API's for some of the keyvalue qsort 

---

lib/x86simdsort.cpp

On MacOS it is the case that `uint64_t` is not the same type as `size_t`, resulting in an error when building the C API code. This changes the input types to all be `uint64_t` instead. It also changes all the length values to be `size_t`, whereas some were `uint32_t` before. Finally, it renames the functions to match their new typings.

Fix and Cleanup C API code

---

src/xss-common-keyvaluesort.hpp
tests/test-keyvalue.cpp
tests/test-qsort-common.h
tests/test-qsort.cpp
utils/rand_array.h

I identified two bugs related to the handling of nans in the kvsort/kvselect logic.
1) kvselect (and thus kvpartialsort) would produce incorrect results when using descending order on arrays with nans
2) kvsort would produce invalid results when given arrays containing both infinity and nan
This patch should fix both of these issues, and it adds a test with mixed inf/nan arrays for all of the qsort/kvsort tests. From my testing, it seems to have a negligible performance impact.

Fix kvsort/kvselect nan behavior and added tests for mixed nan/inf arrays

---

src/avx512-16bit-qsort.hpp
src/xss-common-keyvaluesort.hpp
src/xss-common-qsort.h

Due to some compiler bug, some GCC versions, specifically GCC 9, generate MMX instructions without the required EMMS instruction. This can cause strange and obscure crashes.
A previous version of this problem caused #154, and it now seems to be causing issues with Pytorch. Out of an abundance of caution, this adds defensive EMMS intrinsics to the end of each of the SIMD sorting functions whenever MMX is enabled, to try and make sure this issue never shows up ever again.

Add defensive EMMS instructions to each SIMD sort function

---

.github/workflows/scorecard.yml

This updates the actions in scorecard.yml, hopefully fixing that error it is currently having. The new actions commits and versions are based on [node.js's scorecard.yml](https://github.com/nodejs/node/blob/main/.github/workflows/scorecard.yml)

Hopefully fix scorecard.yml actions

---

src/README.md

Fixes #184 
updated README under src to reflect changes in static method API.

Update readme file for static methods

---

.github/workflows/scorecard.yml

As far as I can tell, self-hosted runners are not really supported by the OSSF scorecard. It used to be on ubuntu-latest, but got changed to intel-ubuntu-24.04, which I believe is what has caused this problem. Hopefully this should fix it.

Change scorecard runner to ubuntu-latest

---

lib/meson.build
src/avx512-16bit-common.h
src/avx512-16bit-qsort.hpp
src/avx512-64bit-common.h
src/avx512fp16-16bit-qsort.hpp
src/xss-common-includes.h
src/xss-common-keyvaluesort.hpp
src/xss-common-qsort.h
tests/meson.build
tests/test-keyvalue.cpp
tests/test-qsort.cpp

This adds OpenMP acceleration to quicksort, in addition to making some changes to the testing code. On my current testing system, this gives up to a 3x speedup, though I think more may be achieved on a stronger system.
Benchmarks:
<details>
<summary><b>10m</b></summary>
```
Comparing simdsort/random_10m (from /home/sterrettm/simd-sort/x86-simd-sort/.bench/main/builddir/benchexe) to simdsort/random_10m (from /home/sterrettm/simd-sort/x86-simd-sort/.bench/qsort-openmp/builddir/benchexe)
Benchmark                                                                       Time             CPU      Time Old      Time New       CPU Old       CPU New
--------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

Adds OpenMP to qsort, should also improve test speed a bit

---

.github/workflows/c-cpp.yml
Makefile
meson.build
meson_options.txt
src/xss-common-qsort.h
tests/meson.build
tests/test-keyvalue.cpp
tests/test-objqsort.cpp
tests/test-qsort-common.h
tests/test-qsort.cpp
utils/rand_array.h

It seems most of the tests were not handling the case where the input size was zero; to be sure these don't misbehave, I've extended those tests to test arrays of size zero. In doing so, I found a few bugs in that handling which should be fixed by this patch. 
In addition, this patch adds a new build option to the makefile `test_asan`, which enabled address sanitizer and undefined behavior sanitizer. This currently only works with clang; GCC seems to show a clearly invalid issue, whereas clang shows no issue there. I also resolved all of the issues found by the undefined behavior sanitizer in this patch.
I'm working on an experimental ASAN CI pipeline, so this is not ready to be merged yet.

Fixes some tests/bugs, and adds a build with sanitizers, add ASAN CI run

---

benchmarks/bench-objsort.hpp
src/xss-common-argsort.h
src/xss-common-keyvaluesort.hpp
src/xss-common-qsort.h
tests/test-qsort.cpp

This patch adds OpenMP support to argsort, in much the same way as quicksort and key-value sort.
Smaller benchmark sizes are included to show that there is not a significant regression for those smaller sizes.
<details>
<summary><b>128/100k/1m/10m/100m Benchmarks</b></summary>
```
Benchmark                                                                         Time             CPU      Time Old      Time New       CPU Old       CPU New
--------------------------------------------------------------------------------------------------------------------------------------------------------------
[simdargsort/random_128/* vs. simdargsort/random_128/*]int64_t                 -0.0066         -0.0060           538           534           537           534
[simdargsort/random_128/* vs. …
```

Add OpenMP support to argsort

---

README.md
meson.build

Added a `declare_dependency` call to `meson.build`, allowing the library to be more easily used as a Meson subproject.

Add Meson dependency declaration for use as a subproject

---

.github/workflows/c-cpp.yml
lib/x86simdsort-icl.cpp
lib/x86simdsort-internal.h
lib/x86simdsort-spr.cpp
lib/x86simdsort.cpp
src/avx512-16bit-qsort.hpp
src/x86simdsort-static-incl.h
src/xss-common-includes.h
src/xss-common-qsort.h
tests/test-qsort.cpp

This patch enabled the non-avx512fp16 _Float16 sorting to be used by the dynamic dispatch logic, as well as integrating it better into the static dispatch logic.
It is vastly faster than scalar, but a fair bit slower then the dedicated avx512fp16 code.
<details>
<summary><b>Comparison to scalar</b></summary>
```
Benchmark                                                       Time             CPU      Time Old      Time New       CPU Old       CPU New
--------------------------------------------------------------------------------------------------------------------------------------------
[scalarsort.*_Float16 vs. simdsort.*_Float16]                -0.9264         -0.9269          6368           468          6373           466
[scalarsort.*_Float16 vs. simdsort.*_Float16] …
```

Enable fp16 nonnative support for dynamic dispatch, make more ergonomic for static dispatch

---

src/avx512-16bit-qsort.hpp
src/xss-common-argsort.h
src/xss-common-includes.h
src/xss-common-keyvaluesort.hpp
src/xss-common-qsort.h

This pull request refactors the logic for determining the number of threads used in parallel sorting functions by introducing a new helper function, `xss_get_num_threads`. This change ensures consistency and simplifies thread count management across multiple sorting implementations.

New helper function to determine number of threads when using openMP

---

lib/meson.build
meson.build
tests/meson.build

Refactor the build system to improve OpenMP support and updates the project version. The most significant changes include replacing manual OpenMP flag handling with Meson's `dependency` mechanism, updating the project version to `7.0.x`, and ensuring consistent dependency declarations across the build files.
* Replaced manual OpenMP flag handling (`openmpflags`) with Meson's `dependency('openmp')` and `declare_dependency` mechanism. This change centralizes OpenMP configuration and simplifies its usage throughout the build files. (`meson.build`, `lib/meson.build`, `tests/meson.build`) [[1]](diffhunk://#diff-30d8f6be6320feeacf686be94f48c70869b52630e01ea625f0f15adc0d57c3e4R32-R39) [[2]](diffhunk://#diff-f95a8510ab53a5e21d9e4a306b12f76fc79086143aa8989c13effed889bec144L3-R11) …

Prep for v7.0 and refactor openMP build flags

---

README.md

This pull request adds documentation on how to enable and use OpenMP for parallel sorting in the project. It explains the configuration steps, performance benefits, and thread control options.
* Added a new section in `README.md` titled "Build using OpenMP." This section details how to enable OpenMP support using the `-Duse_openmp=true` flag in Meson, describes potential performance improvements (up to 3x speedup), and explains how to configure the number of threads using the `OMP_NUM_THREADS` environment variable. It also specifies that OpenMP-based routines are applied to large arrays where threading is beneficial.

update README to include a section on OpenMP

---

.github/workflows/build-numpy.yml
.github/workflows/build-test-on-32bit.sh
.github/workflows/c-cpp.yml
tests/test-objqsort.cpp

Intel SDE version upgraded to use version 9.58.0 (released 2025-06-16), replacing the previous 9.24.0 version.

CI: update Intel SDE version
